spring:
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ihmsdb
    username: root
    password: root

logging:
  level:
    'com.amalvadkar.ihms' : debug
