name: Dev CI

on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Build with Maven
        run: ./mvnw --no-transfer-progress clean verify
        env:
         GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ success() && github.ref == 'refs/heads/develop' }}
        name: Sonar Scan
        run: ./mvnw --no-transfer-progress initialize sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
      
      - if: ${{ github.ref == 'refs/heads/develop' }}
        name: Install Snyk CLI
        run: npm install -g snyk

      - if: ${{ github.ref == 'refs/heads/develop' }}
        name: Run Snyk Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk code test --json > snyk-results.json
          snyk monitor

      - if: ${{ github.ref == 'refs/heads/develop' }}
        name: Convert Snyk results to SARIF
        run: |
          npm install -g snyk-to-sarif
          snyk-to-sarif -i snyk-results.json -o snyk-results.sarif

      - if: ${{ github.ref == 'refs/heads/develop' }}
        name: Upload Snyk results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-results.sarif

  
