name: Dev CI

on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Build with Maven
        run: ./mvnw --no-transfer-progress clean verify
        env:
         GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ success() && github.ref == 'refs/heads/develop' }}
        name: Sonar Scan
        run: ./mvnw --no-transfer-progress initialize sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - if: ${{ github.ref == 'refs/heads/develop' }}
        name: Run Snyk Test
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npm install -g snyk
          snyk code test --sarif > snyk-code.sarif

      - if: ${{ github.ref == 'refs/heads/develop' }}
        name: Snyk Code Test Result Prepare
        continue-on-error: true
        run: snyk code test --json > snyk-report.json

      - if: ${{ github.ref == 'refs/heads/develop' }}
        name: Convert to html report
        continue-on-error: true
        run: npx snyk-to-html ./snyk-report.json > snyk-report.html

      - if: ${{ github.ref == 'refs/heads/develop' }}
        name: Save Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: snyk-report
          path: snyk-report.html

      - if: ${{ github.ref == 'refs/heads/develop' }} 
        name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif

  
